# Generated by Django 3.2.4 on 2021-06-29 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_article_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='editor',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='news.editor'),
        ),
    ]
